name: Publish rspec

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: rspec-gh-pages
          build_dir: spec/reports
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
