name: Railway

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yaml

  publish_yardoc:
    name: Publish pages
    needs: test
    uses: ./.github/workflows/publish_pages.yaml
