name: Railway

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yaml

#  publish_rspec:
#    name: Publish rspec
#    needs: test
#    uses: ./.github/workflows/publish_rspec.yaml

#  publish_coverage:
#    name: Publish coverage
#    needs: test
#    uses: ./.github/workflows/publish_coverage.yaml

  publish_yardoc:
    name: Publish yardoc
    needs: test
    uses: ./.github/workflows/publish_yardoc.yaml
