name: Ruby

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [ '3.1', '2.7' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: bundle install --local

      - name: Run tests
        run: bundle exec rake spec

      - name: Run yard
        run: bundle exec rake yard

      - name: Archive rspec results
        uses: actions/upload-artifact@v3
        with:
          name: public-rspec-results
          path: spec/reports

      - name: Archive coverage results
        uses: actions/upload-artifact@v3
        with:
          name: public-coverage-results
          path: coverage

      - name: Archive yardoc results
        uses: actions/upload-artifact@v3
        with:
          name: public-yardoc-results
          path: doc
